### PR TITLE
Fixing install URL for Craft 3

### PR DESCRIPTION
**Pull request by nickfreedom**
The old URL of http://<HOSTNAME>/index.php?p=admin was "System Offline" errors. Switching to /admin/install seems to resolve the issue.

### CODE REVIEW

**Comment by colinwilson** [comment]
> The old URL of http:///index.php?p=admin was "System Offline" errors

Just to confirm. Are you going to `http://<your hostname>/index.php?p=admin` after install? Just tested this and am seeing the expected behaviour of a 302 redirect to `/admin/install`.

**Comment by nickfreedom** [comment]
No, this is after spinning up the containers for the first time, and before running the Craft install. I did confirm the behavior you described is working, but only _after_ the user has installed Craft.

**Comment by colinwilson** [comment]
Sorry I made a typo, I did actually mean *before* install.

e.g. with my `test.test` domain...
craft3_install_redirect_behaviour2
So you're seeing "System Offline" instead of the above behaviour, correct?

Even though `/admin/install` works fine I just want to check that the [official install url](https://docs.craftcms.com/v3/installation.html#step-6-run-the-setup-wizard) isn't a redirect for any particular reason before accepting your PR.

**Comment by nickfreedom** [comment]
Correct I'm not seeing that behavior. Based on your screenshot though I amended my PR to include both URLs to help with troubleshooting.

**Comment by colinwilson** [comment]
> I amended my PR to include both URLs to help with troubleshooting

Didn't think of that! Thanks :+1:

**Pull request merged**
